'camera_types': ['CAM_FRONT','CAM_BACK_LEFT']

'start_index': 0
'end_index': 1

point_dim: 4

'depth': 10
'min_density': 0.1
'n_threads': 8
'downsample': False
'voxel_size': 0.5
'max_nn': 20
'pc_range':  [-50, -50, -5, 50, 50, 3]
'occ_size':  [200, 200, 16]
'self_range': [3.0, 3.0, 3.0]